from distutils.core import setup

setup(
    name='gdc-snowflake-catalog-sync',
    version='',
    packages=['tests', 'tests.unit', 'lambdalibpackages', 'lambdalibpackages.python', 'lambdalibpackages.python.jwt',
              'lambdalibpackages.python.attr', 'lambdalibpackages.python.cffi', 'lambdalibpackages.python.idna',
              'lambdalibpackages.python.attrs', 'lambdalibpackages.python.jinja2', 'lambdalibpackages.python.certifi',
              'lambdalibpackages.python.urllib3', 'lambdalibpackages.python.urllib3.util',
              'lambdalibpackages.python.urllib3.contrib', 'lambdalibpackages.python.urllib3.contrib._securetransport',
              'lambdalibpackages.python.urllib3.packages', 'lambdalibpackages.python.urllib3.packages.backports',
              'lambdalibpackages.python.requests', 'lambdalibpackages.python.pycparser',
              'lambdalibpackages.python.pycparser.ply', 'lambdalibpackages.python.markupsafe',
              'lambdalibpackages.python.cryptography', 'lambdalibpackages.python.cryptography.x509',
              'lambdalibpackages.python.cryptography.hazmat', 'lambdalibpackages.python.cryptography.hazmat.backends',
              'lambdalibpackages.python.cryptography.hazmat.backends.openssl',
              'lambdalibpackages.python.cryptography.hazmat.bindings',
              'lambdalibpackages.python.cryptography.hazmat.bindings.openssl',
              'lambdalibpackages.python.cryptography.hazmat.primitives',
              'lambdalibpackages.python.cryptography.hazmat.primitives.kdf',
              'lambdalibpackages.python.cryptography.hazmat.primitives.ciphers',
              'lambdalibpackages.python.cryptography.hazmat.primitives.twofactor',
              'lambdalibpackages.python.cryptography.hazmat.primitives.asymmetric',
              'lambdalibpackages.python.cryptography.hazmat.primitives.serialization',
              'lambdalibpackages.python.charset_normalizer', 'lambdalibpackages.python.charset_normalizer.cli',
              'lambdalibpackages.python.charset_normalizer.assets', 'gdc_snowflake_catalog_sync'],
    url='',
    license='',
    author='Srividya Parthasarathy',
    author_email='',
    description=''
)
